### ISSUE TITLE
Can't train 3DGS on export_to_colmap results

### ISSUE THREAD

**Issue by salernosimone** [ByteDance-Seed/Depth-Anything-3#117]
I exported predictions to Colmap format using `export_to_colmap` function: it generates `points3D.bin`, `images.bin`, `frames.bin`, `cameras.bin` and `rigs.bin`. I note here that for 300 images it generates 20M points with a confidence percentile of 70.

Next, I tried to run `train.py` from original gaussian splatting repo (`graphdeco-inria`) but I consistently get this error:

```
Converting point3d.bin to .ply, will happen only the first time you open the scene. [28/11 23:25:12]
Loading Training Cameras [28/11 23:26:20]
Loading Test Cameras [28/11 23:26:48]
Number of points at initialisation :  12827810 [28/11 23:26:49]

[gpu-health] [WARN] GPU-a2edc31e-63f6-ebc5-f156-ed40ee9f221b: XID: NVRM: Xid (PCI:0000:ca:00): 31, pid=1907695, name=exe, Ch 00000008, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC11 GPCCLIENT_T1_0 faulted @ 0x2b0d_7b7bf000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
Training progress:   0%|          | 0/7000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/app/gaussian-splatting/train.py", line 282, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/app/gaussian-splatting/train.py", line 142, in training
    loss.backward()
  File "/opt/conda/envs/torch/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/opt/conda/envs/torch/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/opt/conda/envs/torch/lib/python3.10/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   0%|          | 0/7000 [00:00<?, ?it/s]
```

Can you help me understand? Are there too many points?

**Comment by Jaykumaran** [comment]
Hello,

You have mentioned that the exported points bin file has 20M points, however from the logs i could see is number of points at initialisation has ~12M . This kinda a error like CUDA illegal mem access occured for me when i ran VGGT long to obtain the point cloud and cleaned it manually and try to train 3dgs. This might be due to the case where the colmap exported file had a set of points ID but the loaded points during gaussian is less, due to NAN or missing values.

As a sanity check you can consider on any other typical sample datasets and try to train 3dgs to better understand the issue.

**Comment by xgx10010** [comment]
hello everyone, I also wonder another problem for the training cost on such 20M initial points. It seems too dense but low-qulity. How to work with such 20M? Any good method rather than just sampling? thanks

**Comment by Jaykumaran** [comment]
You can consider limiting the number of gaussians spawned initially in your 3dgs training?!   or try extremely sparse sampling like conf 0.99 and ratio 0.005 or so

**Comment by salernosimone** [comment]
Thanks @Jaykumaran for looking this up. I did several trials with varying numbers of points, I probably confused the error log. Still the problem exists, since I'm using the `export_to_colmap` straight from this library: is it not working properly?

Also, I second the @xgx10010 comment: any particular reason for so many points? For the same dataset Colmap produced a 30Mb points3D file, while DA3 file weighted 1.2Gb.

**Comment by xgx10010** [comment]
because the prediction result is pixel-aligned

**Comment by shine157** [comment]
Hello, could you tell me if you have found a suitable alternative to COLMAP?

**Comment by wurara7** [comment]
My experiments tell me that the camera poses exported by DA3 are inconsistent with those used for 3DGS training. Occasionally, the cameras unexpectedly point to empty regions, resulting in some buffers having a length of 0 and thus triggering CUDA errors (maybe

**Comment by salernosimone** [comment]
@shine157 I didn't yet
@wurara7 can this be fixed in `export_to_colmap` code?

**Comment by soohyoen** [comment]
Did anyone solve it?

**Comment by Jaykumaran** [comment]
> Hello, could you tell me if you have found a suitable alternative to COLMAP?

Try RealityCapture, I always use on any arbitary datasets or video it works whereas colmap fails, 

you may need a windows machine, not sure whether it would work in Linux with Wine

**Comment by Jaykumaran** [comment]
> Did anyone solve it?

With DA3, export colmap there could a possible bug, however if your interested in alternatives

1. https://github.com/msilaev/VGGT-Long-Gsplat
2. https://github.com/Linketic/VGGT-X

Unline VGGT_Long or DA3 colmap exports where the 3DS training is a complete mess, VGGT-X and VGGT_Long_GSplat methods to some extend rendered decent outputs though still not as good as colmap/reality SFM -- i tested some mobile capture- outdoor sequences
